import { useState } from 'react'
import AppLayout from '../layouts/AppLayout'
import { useStore } from '../services/store'
import { adherencePercent, weeklyTrend } from '../utils/adherence'
import { api } from '../services/api'
import { useToast } from '../components/Toast'

export default function Adherence() {
  const events = useStore((s) => s.events)
  const show = useToast((s) => s.show)
  const todays = events.filter((e) => e.date === 'today')
  const pct = adherencePercent(todays)
  const trend = weeklyTrend(pct)

  const [summaryText, setSummaryText] = useState<string | null>(null)
  const [loadingSummary, setLoadingSummary] = useState(false)

  const handleGenerateSummary = async () => {
    setLoadingSummary(true)
    try {
      const summary = await api.generateDoctorSummary({
        patient_name: 'Ramesh Sharma',
        adherence_percentage: pct,
        weekly_trend: trend,
        missed_evening_count: 2,
      })
      setSummaryText(summary)
      show('Doctor summary generated by AI')
    } finally {
      setLoadingSummary(false)
    }
  }

  return (
    <AppLayout title="Adherence & Clinical Analytics" meta="Daily compliance, temporal patterns & doctor consultation summary">
      {/* Top 4 Stats */}
      <div className="grid grid-cols-4 gap-4">
        <Stat k="Overall adherence" v={`${pct}%`} />
        <Stat k="Morning doses" v="100%" />
        <Stat k="Evening doses" v="50%" />
        <Stat k="Adherence Streak" v="5 Days 🔥" />
      </div>

      {/* 7-Day Trend Bar Chart */}
      <div className="panel">
        <h3 className="text-[16px] font-semibold text-teal-950 mb-4">7-day Adherence Trend</h3>
        {trend.map(({ day, pct: v }) => (
          <div key={day} className="flex items-center gap-3 mb-2.5">
            <div className="w-[38px] text-[12.5px] text-inksoft">{day}</div>
            <div className="bar-track flex-1">
              <div className="bar-fill" style={{ width: `${v}%` }} />
            </div>
            <div className="w-9 text-[12.5px] text-right font-semibold">{v}%</div>
          </div>
        ))}
      </div>

      {/* ML Temporal Pattern Alert */}
      <div className="panel border-l-4 border-amber-500">
        <div className="flex justify-between items-center mb-2">
          <h3 className="text-[16px] font-semibold text-teal-950">ML Temporal Pattern Identified</h3>
          <span className="text-[11px] font-bold px-2 py-0.5 rounded bg-amber-100 text-amber-900 uppercase">
            Random Forest Classifier
          </span>
        </div>
        <div className="alert-box alert-warn text-[14px]">
          ⚠️ <b>Evening Adherence Drop-off:</b> Evening doses (8:30 PM Metformin) are missed significantly more often than morning doses. The model recommends shifting the reminder window to dinner time (8:00 PM).
        </div>
      </div>

      {/* Doctor Summary Synthesis Section */}
      <div className="panel bg-gradient-to-r from-teal-50 to-white border border-teal-200">
        <div className="flex justify-between items-center mb-3">
          <div>
            <h3 className="text-[17px] font-semibold text-teal-950">Doctor Visit Adherence Summary</h3>
            <p className="text-[13.5px] text-inksoft">
              Generate a synthesized clinical briefing note to bring to your next doctor visit.
            </p>
          </div>
          <button className="btn-primary" onClick={handleGenerateSummary} disabled={loadingSummary}>
            {loadingSummary ? 'Synthesizing with Gemini...' : '📄 Generate Doctor Summary'}
          </button>
        </div>

        {summaryText && (
          <div className="mt-4 p-4 rounded-xl bg-white border border-teal-300 shadow-sm">
            <div className="flex justify-between items-center mb-2">
              <span className="text-[12px] font-bold text-teal-800 uppercase tracking-wider">
                Clinical Briefing Note for Physician
              </span>
              <button
                className="text-[12px] text-inksoft hover:text-black font-semibold"
                onClick={() => {
                  navigator.clipboard.writeText(summaryText)
                  show('Summary copied to clipboard')
                }}
              >
                📋 Copy
              </button>
            </div>
            <pre className="text-[13.5px] font-sans leading-relaxed text-ink whitespace-pre-wrap">
              {summaryText}
            </pre>
          </div>
        )}
      </div>
    </AppLayout>
  )
}

function Stat({ k, v }: { k: string; v: string }) {
  return (
    <div className="bg-paper border border-line rounded-2xl p-5">
      <div className="text-[12.5px] text-inksoft font-semibold">{k}</div>
      <div className="text-[26px] font-semibold text-teal-950 mt-1.5">{v}</div>
    </div>
  )
}
